name: test

networks:
  main:

services:
  crond:
    image: alpine:3.23.5@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40
    command: ['crond', '-f', '-d8']
    init: true
    restart: unless-stopped
    networks:
      - main
