name: Check GitHub Actions Workflows

on:
  push:
    branches:
      - $default-branch
      - 'renovate/**'
    paths: &paths
      - '.github/workflows/*.ya?ml'

  pull_request:
    branches:
      - $default-branch
    paths: *paths

  workflow_call:
  workflow_dispatch:

jobs:
  _:
    uses: jonasgeiler/.github/.github/workflows/check-github-actions-workflows.yaml@main
    with:
      override-globs: >-
        workflow-templates/*.{yml,yaml}
        action.{yml,yaml}
