name: Check Shell Scripts

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths: &paths
      - '**.ash'
      - '**.bash'
      - '**.bats'
      - '**.dash'
      - '**.ksh'
      - '**.sh'
      - '.githooks/*'

      # Currently fails in the ".github" repo because no shell scripts exist.
      #- .github/workflows/check-shell-scripts.ya?ml

  pull_request:
    branches:
      - main
    paths: *paths

  workflow_call:
    inputs: &inputs
      additional-globs:
        description: 'Additional, space-separated glob patterns (or files) to check with ShellCheck.'
        type: string
        required: false
        default: ''

  workflow_dispatch:
    inputs: *inputs

jobs:
  code-quality:
    name: Code Quality

    # We are using ubuntu-slim because it is a really fast little job.
    runs-on: ubuntu-slim
    defaults:
      run:
        shell: bash --noprofile --norc -euxo pipefail {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up ShellCheck
        env:
          # renovate: datasource=github-releases depName=koalaman/shellcheck
          SHELLCHECK_VERSION: v0.11.0
          # renovate: datasource=github-releases depName=lumaxis/shellcheck-problem-matchers
          SHELLCHECK_PROBLEM_MATCHERS_VERSION: v2.1.0
        run: |
          # Create a temporary download directory.
          download_dir="$(mktemp -d -p "${RUNNER_TEMP}")"

          # Check if ShellCheck is already cached.
          shellcheck_cache_dir="${RUNNER_TOOL_CACHE}/shellcheck/${SHELLCHECK_VERSION#v}/x64"
          shellcheck_cache_complete="${shellcheck_cache_dir}.complete"
          if [[ ! -f "${shellcheck_cache_complete}" ]]; then
            # Download the ShellCheck archive.
            shellcheck_archive_download="${download_dir}/shellcheck.tar.xz"
            curl \
              --fail \
              --silent \
              --show-error \
              --location \
              "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" \
              --output "${shellcheck_archive_download}"

            # Clean up any existing cache files.
            if [[ -d "${shellcheck_cache_dir}" ]]; then
              rm -rf "${shellcheck_cache_dir}"
            fi
            mkdir -p "${shellcheck_cache_dir}"

            # Extract the ShellCheck binary from the archive into the cache directory.
            tar \
              --extract \
              --warning 'no-unknown-keyword' \
              --auto-compress \
              --file "${shellcheck_archive_download}" \
              --overwrite \
              --directory "${shellcheck_cache_dir}" \
              --strip-components 1 \
              "shellcheck-${SHELLCHECK_VERSION}/shellcheck"

            # Finalize the binary and add it to the PATH.
            chmod +x "${shellcheck_cache_dir}/shellcheck"
            echo "${shellcheck_cache_dir}" >> "${GITHUB_PATH}"

            # Mark the ShellCheck cache as complete.
            echo '' > "${shellcheck_cache_complete}"
          fi

          # Download the ShellCheck problem matcher.
          shellcheck_problem_matcher_download="${download_dir}/shellcheck-problem-matcher.json"
          curl \
            --fail \
            --silent \
            --show-error \
            --location \
            "https://raw.githubusercontent.com/lumaxis/shellcheck-problem-matchers/refs/tags/${SHELLCHECK_PROBLEM_MATCHERS_VERSION}/.github/shellcheck-gcc.json" \
            --output "${shellcheck_problem_matcher_download}"

          # Register the ShellCheck problem matcher.
          echo "::add-matcher::${shellcheck_problem_matcher_download}"

      - name: Run ShellCheck
        run: |
          # Support advanced globbing patterns.
          shopt -s dotglob globstar nullglob

          # We have to use gcc format and disable colors for the problem matcher.
          # The additional-globs are injected as-is, so each is an argument.
          shellcheck --norc --format=gcc --color=never \
            ${{ inputs.additional-globs }} \
            ./**/*.{ash,bash,bats,dash,ksh,sh} \
            .githooks/*
